remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- attr_list
font:
  normal:
    family: "MiSans Latin VF"
    style: "Regular"
  bold:
    family: "MiSans Latin VF"
    style: "Bold"
  italic:
    family: "MiSans Latin VF"
    style: "Italic"
  bold_italic:
    family: "MiSans Latin VF"
    style: "Bold Italic"

